# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dummy1_cpp <- function(args) {
    .Call(`_MIPanalyzer_dummy1_cpp`, args)
}

inbreeding_mle_cpp <- function(args, args_functions, args_progress) {
    .Call(`_MIPanalyzer_inbreeding_mle_cpp`, args, args_functions, args_progress)
}

